### ISSUE TITLE
Overload error

### ISSUE THREAD

**Issue by toms77** [Wappsto/arduino_wappstoiot#10]
Getting overload errors when compiling 

Value.cpp:227:51: error: call of overloaded 'String(double&, uint8_t&)' is ambiguous

**Comment by TsvetomirIvanov** [comment]
The current version of the Arduino WappstoIoT library supports only ESP32 library version 1.0.x. The ESP32 library version we are testing with is 1.0.6.

**Comment by TsvetomirIvanov** [comment]
As of version [0.1.0](https://github.com/Wappsto/arduino_wappstoiot/releases/tag/0.1.0) ESP 2.0.x is also supported
